import re
s="an apple a day keeps doctor away!!!!"
ans=re.findall('a\w',s)
print(ans)
ans=re.findall('a\w+',s)
print(ans)
ans=re.findall('a\w*',s)
print(ans)
ans=re.findall(r'\ba\w+\b',s)
print(ans)
ans=re.findall(r'\ba\w?\b',s)
print(ans)
ans=re.findall(r'\ba\w{4}\b',s)
print(ans)
ans=re.findall(r'\b\w{3,5}\b',s)
print(ans)
ans=re.findall(r'\b\w{ ,5}\b',s)
print(ans)
ans=re.findall(r'\b\w{3, }\b',s)
print(ans)
ans=re.findall('^the',s)
print(ans)
ans=re.findall('.$',s)
print(ans)
ans=re.findall('a[^a-d]+',s)
print(ans)